### ISSUE TITLE
关于预训练完成后合并模型及SFT的问题

### ISSUE THREAD

**Issue by charryshi** [shibing624/MedicalGPT#14]
感谢作者。想按您的项目中的资料来尝试全流程，已经基于Ziya-LLaMA-13B-v1做了Lora的增量预训练，然后按文档将第一阶段的Lora和Base模型合并
python merge_peft_adapter.py \
>   --base_model_name_or_path ~/Ziya-LLaMA-13B-v1/ \
>   --peft_model_path ~/MedicalGPT/outputs-pt-v1/ \
>   --output_dir outputs-merged \
> --model_type llama
再将model_name_or_path指定为合并后的模型文件夹开始sft时出错

运行run_sft.sh时报了很多
/opt/conda/conda-bld/pytorch_1682343962757/work/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [182,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
这样的错，

Traceback (most recent call last):
  File "supervised_finetuning.py", line 549, in <module>
    main()
  File "supervised_finetuning.py", line 520, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/transformers/trainer.py", line 1940, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/transformers/trainer.py", line 2735, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/transformers/trainer.py", line 2767, in compute_loss
    outputs = model(**inputs)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/peft/peft_model.py", line 678, in forward
    return self.base_model(
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 537, in forward
    attention_mask = self._prepare_decoder_attention_mask(
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 465, in _prepare_decoder_attention_mask
    combined_attention_mask = _make_causal_mask(
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 49, in _make_causal_mask
    mask = torch.full((tgt_len, tgt_len), torch.tensor(torch.finfo(dtype).min, device=device), device=device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

  0%|                                                   | 0/125 [00:00<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 107253) of binary: /home/xxx/miniconda3/envs/torch/bin/python
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/torch/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xxx/miniconda3/envs/torch/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

但如果我直接在sft时指定使用原始模型~/Ziya-LLaMA-13B-v1/进行sft就没问题
第一阶段生成Lora文件正常也未报错，merge_peft_adapter前Lora文件和原始基础模型一起用inference.py跑推理测试也正常

合并的outputs-merged目录下文件如下
added_tokens.json
config.json
generation_config.json
pytorch_model-00001-of-00003.bin
pytorch_model-00002-of-00003.bin
pytorch_model-00003-of-00003.bin
pytorch_model.bin.index.json
special_tokens_map.json
tokenizer_config.json
tokenizer.model

请问您合并后的模型文件做sft出错可能会是什么原因呀

**Comment by dadaxxxx** [comment]
我也遇到同样的问题

**Comment by shibing624** [comment]
我测试下，是只有llama有这个问题，还是bloom等也会出现？

**Comment by charryshi** [comment]
感谢，我是在LLaMA下测试出现的，使用的基础模型是您项目中例子的Ziya-LLaMA-13B-v1，bloom我没测过不确认。

**Comment by shibing624** [comment]
add bloom training_pipeline https://colab.research.google.com/github/shibing624/MedicalGPT/blob/main/run_training_pipeline.ipynb

**Comment by randyadd163** [comment]
bloom，测试最新的代码是可以的，bloom 3B没做pt，直接做的sft，模型合并成功的。

**Comment by shibing624** [comment]
> add bloom training_pipeline https://colab.research.google.com/github/shibing624/MedicalGPT/blob/main/run_training_pipeline.ipynb

这个是我跑完全流程的，包括各个Stage merge lora，我测试下llama。

**Comment by dadaxxxx** [comment]
请求这个问题解决了么？

**Comment by charryshi** [comment]
我把缓存清理了重新把tokenizer做了一次，代码里强制了一次tokenizer.pad_token_id = 0 ，后面再运行就正常了

**Comment by 1615070057** [comment]
> tokenizer.pad_token_id = 0
测试可以, 这是为啥呢

**Comment by shibing624** [comment]
> > tokenizer.pad_token_id = 0
> > 测试可以, 这是为啥呢

原因是llama的预训练模型，未设置pad_token和pad_token_id，SFT阶段需要padding input_ids，会造成数组越界错误。

最新代码已经fixed这个问题了。
